### ISSUE TITLE
How to use backend for real-time

### ISSUE THREAD

**Issue by ERGOWHO** [princeton-vl/DROID-SLAM#122]
In the droid.py  self.backend() is commented. But I need to run real-time Global Boundle Adjust ment for each keyframe for my project. 

If I keep self.backend(), it will have error :

0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/splatmap/demo.py", line 431, in <module>
    poses, disps= droid.track(t, image, intrinsics=intrinsics)
  File "/home/splatmap/droid_slam/droid.py", line 123, in track
    self.backend(1)
  File "/home/miniconda3/envs/splatmap/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/splatmap/droid_slam/droid_backend.py", line 34, in __call__
    graph.add_proximity_factors(rad=self.backend_radius,
  File "/home/splatmap/droid_slam/factor_graph.py", line 374, in add_proximity_factors
    ii, jj = torch.as_tensor(es, device=self.device).unbind(dim=-1)
ValueError: not enough values to unpack (expected 2, got 0)

Anyone have any idea for this issue?

**Comment by 2cu-1001** [comment]
Can you share how you solved this problem please? Thank you
