### ISSUE TITLE
No module named 'droid_backends'

### ISSUE THREAD

**Issue by weilairenlei2020** [princeton-vl/DROID-SLAM#4]
Traceback (most recent call last):
  File "demo.py", line 15, in <module>
    from droid import Droid
  File "/home/vip/DROID-SLAM/droid_slam/droid.py", line 5, in <module>
    from droid_net import DroidNet
  File "/home/vip/DROID-SLAM/droid_slam/droid_net.py", line 8, in <module>
    from modules.corr import CorrBlock
  File "/home/vip/DROID-SLAM/droid_slam/modules/corr.py", line 4, in <module>
    import droid_backends
ModuleNotFoundError: No module named 'droid_backends'

The code is missing this module,How to solve it!?
Thanks!

**Comment by denred0** [comment]
@weilairenlei2020 just run python setup.py install
