### ISSUE TITLE
Errors During Demo execution 

### ISSUE THREAD

**Issue by pradyumnakulkarni87** [princeton-vl/DROID-SLAM#51]
File "/home/itadmin/DROID-SLAM/demo.py", line 100, in <module>
    droid = Droid(args)
  File "/home/itadmin/DROID-SLAM/droid_slam/droid.py", line 37, in __init__
    from visualization import droid_visualization
  File "/home/itadmin/DROID-SLAM/droid_slam/visualization.py", line 8, in <module>
    import open3d as o3d
ModuleNotFoundError: No module named 'open3d'

kidly help me out

**Comment by pradyumnakulkarni87** [comment]
Traceback (most recent call last):
  File "/home/itadmin/anaconda3/envs/DRD_POC/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/itadmin/anaconda3/envs/DRD_POC/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/itadmin/DROID-SLAM/droid_slam/visualization.py", line 145, in droid_visualization
    vis = o3d.visualization.VisualizerWithKeyCallback()
AttributeError: module 'open3d' has no attribute 'visualization'
267it [00:48,  1.19it/s]
......But we can see the VDO 

KIndly help me out

**Comment by Shahrullo** [comment]
@pradyumnakulkarni87 you have to install `open3d` -  `pip install open3d`
